require './f5'
require 'optparse'
require 'pp'
require 'ruby-debug'
require 'ostruct'

class Optparser
  def self.parse(args)
    options = OpenStruct.new

    opts = OptionParser.new do |opts|
      
      opts.banner = "Usage: f5_vs_get_profile.rb [options]"
      opts.separator ""
      opts.separator "Specific options:"
          
      opts.on( "-b", "--bigip IP", "BigIP IP address") do |bip|
        options.bigip = bip
      end
      opts.on("-n", "--name VS_NAME", "Name of virtual server") do |name|
        options.name = name
      end
      
      opts.on_tail("-h", "--help", "Show this message") do
        puts opts
      exit
      end
    end
    opts.parse!(args)
    options
  end # self.parse
end #class Optparser


def get_vs_profile(lb, vs_list)
  #debugger
  lb.icontrol.locallb.virtual_server.get_profile(vs_list)
end

# get command line options
options = Optparser.parse(ARGV)


REQ_PARAMS = [:bigip, :name]
REQ_PARAMS.find do |p|
  Kernel.abort "Missing Argument: #{p}" unless options.respond_to?(p)
end

lb = F5::LoadBalancer.new(options.bigip, :config_file => '../fixtures/config-andy.yaml', :connect_timeout => 10)

vs_list = [options.name]
vs_list = ["storefront.commerce.perf.corp.theplatform.com_80",
"data.media.perf.corp.theplatform.com_80",
"shard.upload.mpx.sandbox.theplatform.com_443",
"address.commerce.sandbox.corp.theplatform.com_443",
"bskyb-demo.sandbox.theplatform.com_80",
"shard.data.entertainment.tv.sandbox.theplatform.com_80",
"shard.fms.sandbox.theplatform.com_443",
"shoppingcart.commerce.sandbox.corp.tp.com_443",
"admin.storefront.commerce.sandbox.theplatform.com_443",
"shard.data.task.sandbox.theplatform.com_80",
"fms.perf.corp.theplatform.com_80",
"address.commerce.perf.corp.theplatform.com_80",
"promotion.commerce.sandbox.theplatform.com_443",
"ledger.commerce.perf.corp.theplatform.com_80",
"fms.dev.corp.theplatform.com_80",
"shard.upload.mpx.sandbox.theplatform.com_80",
"feedservice.product.alu.sandbox.theplatform.com_80",
"pdk.sandbox.theplatform.com_80",
"shard.fms.sandbox.theplatform.com_80",
"shard.publish.sandbox.theplatform.com_80",
"shard.data.task.sandbox.theplatform.com_443",
"TestWebB_80",
"access.admin.self.corp.theplatform.com_80",
"access.auth.dev.corp.tp.com_80",
"access.auth.test.corp.tp.com_80",
"access.user.self.corp.theplatform.com_80",
"accesschecker.corp.theplatform.com_443",
"accesschecker.corp.theplatform.com_80",
"acs.euid.sandbox.theplatform.com_443",
"acs.euid.sandbox.tp.com_80",
"acs.euid.test.tp.com_443",
"acs.euid.test.tp.com_80",
"adapter.ingest.sandbox.tp.com_80",
"adapter.ingest.self.corp.theplatform.com_80",
"adapter.ingest.test.corp.theplatform.com_80",
"address.commerce.sandbox.corp.theplatform.com_80",
"admin.sandbox.tp.com_443",
"admin.sandbox.tp.com_80",
"admin.storefront.commerce.sandbox.theplatform.com_80",
"autopublish.sandbox.tp.com_80",
"bt.access.admin.test.corp.tp.com_80",
"bt.access.user.test.corp.tp.com_80",
"bt.admin-origin.test.corp.theplatform.com_80",
"bt.admin-origin.test.corp.theplatform.com_8081",
"bt.admin.test.corp.theplatform.com_443",
"bt.admin.test.corp.theplatform.com_80",
"bt.checkout.test.corp.theplatform.com_80",
"bt.data.delivery-origin.test.corp.theplatform.com_80",
"bt.data.ingest.test.corp.tp.com_80",
"bt.data.key.entitlement.test.corp.theplatform.com_8081",
"bt.data.mpx.test.corp.theplatform.com_80",
"bt.data.publish-origin.test.corp.theplatform.com_80",
"bt.data.sharing-origin.test.corp.theplatform.com_80",
"bt.data.validation-origin.test.corp.theplatform.com_80",
"bt.data.watchfolder.test.corp.theplatform.com_80",
"bt.data.workflow-origin.test.corp.theplatform.com_80",
"bt.entitlement.test.corp.tp.com_80",
"bt.event.sandbox.theplatform.com_80",
"bt.facade.test.corp.theplatform.com_80",
"bt.fulfillment.test.corp.theplatform.com_80",
"bt.identity.admin.test.corp.tp.com_80",
"bt.identity.user.test.corp.tp.com_80",
"bt.ingest.test.corp.tp.com_80",
"bt.ledger.test.corp.theplatform.com_80",
"bt.link-origin.test.corp.theplatform.com_80",
"bt.mpx.test.corp.theplatform.com_80",
"bt.playready.entitlement.test.corp.theplatform.com_80",
"bt.proxy.sandbox.theplatform.com_443",
"bt.proxy.sandbox.theplatform.com_80",
"bt.publish-origin.test.corp.theplatform.com_80",
"bt.release-origin.test.corp.theplatform.com_80",
"bt.release-origin.test.corp.theplatform.com_8081",
"bt.release.test.corp.theplatform.com_443",
"bt.release.test.corp.theplatform.com_80",
"bt.task-origin.test.corp.theplatform.com_80",
"bt.task-origin.test.corp.theplatform.com_8081",
"bt.task.test.corp.theplatform.com_443",
"bt.task.test.corp.theplatform.com_80",
"bt.userprofile.test.corp.theplatform.com_80",
"bt.vosp-2.test.corp.theplatform.com_80",
"bt.vosp-3.test.corp.theplatform.com_80",
"bt.vosp.test.corp.theplatform.com_80",
"bt.wm.entitlement.test.corp.theplatform.com_8081",
"cached.read.mps.sandbox.theplatform.com_80",
"cached2.read.mps.sandbox.theplatform.com_80",
"cbc.feed.perf.corp.theplatform.com_80",
"cbc.read.mps.perf.corp.theplatform.com_80",
"cbs.ingest.sandbox.theplatform.com_80",
"cbs.ingest.test.corp.theplatform.com_80",
"checkout.commerce.sandbox.theplatform.com_80",
"checkout.commerce.test.corp.theplatform.com_80",
"choices.community.sandbox.tp.com_80",
"cim.customcommand.sandbox.tp.com_80",
"cim.customcommand.test.corp.theplatform.com_80",
"comments.community.sandbox.tp.com_80",
"concurrency.delivery.sandbox.theplatform.com_443",
"concurrency.delivery.self.corp.theplatform.com_80",
"concurrency.delivery.test.corp.theplatform.com_443",
"connector.sandbox.tp.com_80",
"data.acs.euid.sandbox.theplatform.com_80",
"data.acs.euid.test.corp.theplatform.com_80",
"data.community.sandbox.tp.com_80",
"data.community.test.corp.theplatform.com_80",
"data.configuration.commerce.sandbox.theplatform.com_80",
"data.configuration.commerce.test.corp.theplatform.com_80",
"data.delivery.sandbox.theplatform.com",
"data.delivery.sandbox.theplatform.com_443",
"data.delivery.self.corp.theplatform.com_80",
"data.delivery.test.corp.theplatform.com_80",
"data.entertainment.tv.sandbox.theplatform.com_80",
"data.entertainment.tv.test.corp.theplatform.com_80",
"data.entitlement.sandbox.theplatform.com",
"data.entitlement.sandbox.theplatform.com-schemaruletest_80",
"data.entitlement.self.corp.theplatform.com_80",
"data.entitlement.test.corp.theplatform.com_80",
"data.feed.sandbox.tp.com_80",
"data.feed.test.corp.tp.com_80",
"data.key.entitlement.sandbox.corp.theplatform.com_443",
"data.key.entitlement.self.corp.theplatform.com_80",
"data.key.test.corp.theplatform.com_80",
"data.listing.tv.sandbox.theplatform.com_80",
"data.listing.tv.test.corp.theplatform.com_80",
"data.manage.sandbox.tp.com_80",
"data.media.oracle.test.corp.theplatform.com_80",
"data.media.perf.sandbox.corp.theplatform.com_80",
"data.media.sandbox.theplatform.com_80",
"data.media.test.corp.tp.com_80",
"data.message.sandbox.theplatform.com_80",
"data.message.self.corp.theplatform.com_80",
"data.message.test.corp.theplatform.com_80",
"data.mpx.long.test.corp.theplatform.com_80",
"data.mpx.oralong.test.corp.theplatform.com_80",
"data.mpx.orashort.test.corp.theplatform.com_80",
"data.mpx.self.corp.theplatform.com_80",
"data.mpx.short.test.corp.theplatform.com_80",
"data.mpx.test.corp.tp.com_80",
"data.player.sandbox.theplatform.com_443",
"data.player.sandbox.theplatform.com_80",
"data.player.test.corp.theplatform.com_80",
"data.product.sandbox.theplatform.com_80",
"data.product.test.corp.theplatform.com_80",
"data.publish.sandbox.theplatform.com_80",
"data.publish.self.corp.theplatform.com_80",
"data.registry.sandbox.tp.com_80",
"data.registry.test.corp.tp.com_80",
"data.share.sandbox.tp.com_80",
"data.share.self.corp.theplatform.com_80",
"data.share.test.corp.theplatform.com_80",
"data.social.community.sandbox.theplatform.com_443",
"data.social.community.sandbox.theplatform.com_80",
"data.social.community.test.corp.theplatform.com_80",
"data.somdccdn.test.corp.theplatform.com_80",
"data.task.sandbox.corp.theplatform.com_80",
"data.task.sandbox.theplatform.com_80",
"data.task.self.corp.theplatform.com_80",
"data.task.test.corp.tp.com_443",
"data.task.test.corp.tp.com_80",
"data.userprofile.community.sandbox.theplatform.com_443",
"data.userprofile.community.sandbox.theplatform.com_80",
"data.userprofile.community.test.corp.theplatform.com_80",
"data.validation.sandbox.tp.com_80",
"data.validation.test.corp.tp.com_80",
"data.watchfolder.self.corp.theplatform.com_80",
"data.workflow.sandbox.theplatform.com_443",
"data.workflow.sandbox.theplatform.com_80",
"data.workflow.self.corp.theplatform.com_80",
"demo.sandbox.corp.theplatform.com_21",
"demo.theplatform.com_80",
"devauthmps.test.corp.theplatform.com_80",
"disney.keychest.sync.sandbox.theplatform.com_80",
"dmm.sandbox.tp.com_80",
"enduser.access.auth.dev.corp.theplatform.com_80",
"enduser.access.auth.test.corp.tp.com_80",
"entitlement.commerce.sandbox.tp.com_80",
"entitlement.sandbox.corp.tp.com_80",
"entitlement.sandbox.theplatform.com_80",
"entitlement.self.corp.theplatform.com_80",
"entitlement.test.corp.theplatform.com_80",
"euid.dev.corp.theplatform.com_80",
"euid.test.corp.tp.com_443",
"euid.test.corp.tp.com_80",
"euns.commerce.sandbox.corp.tp.com_80",
"fancast.index.sandbox.corp.theplatform.com_80",
"fancast.search.sandbox.theplatform.com_80",
"feed.product.alu.sandbox.theplatform.com_80",
"feed.sandbox.tp.com_80",
"feed.self.corp.theplatform.com_80",
"feed.test.corp.tp.com",
"feedreader.ingest.sandbox.tp.com_443",
"feedreader.ingest.sandbox.tp.com_80",
"feedreader.ingest.self.corp.theplatform.com_80",
"feedreader.ingest.test.corp.tp.com_80",
"feeds-origin.self.corp.theplatform.com_80",
"feeds.sandbox.tp.com_80",
"flashaccess.entitlement.sandbox.theplatform.com_80",
"flashaccess.entitlement.test.corp.theplatform.com_80",
"fms.sandbox.theplatform.com_80",
"fms.self.corp.theplatform.com_80",
"fms.test.corp.theplatform.com_80",
"fulfillment.commerce.sandbox.corp.tp.com_80",
"fulfillment.commerce.sandbox.theplatform.com_80",
"httpstreams.sandbox.theplatform.com_80",
"identity.admin.self.corp.theplatform.com_443",
"identity.auth.dev.corp.tp.com_80",
"identity.auth.test.corp.tp.com_443",
"identity.auth.test.corp.tp.com_80",
"identity.user.self.corp.theplatform.com_443",
"indemand.checkout.commerce.sandbox.corp.tp.com_80",
"indemand.connector.sandbox.corp.tp.com_80",
"indemand.connector.sandbox.tp.com_80",
"indemand.index.sandbox.corp.tp.com_80",
"indemand.loomia.sandbox.corp.tp.com_80",
"indemand.loomia.sandbox.tp.com_80",
"indemand.promoadmin.sandbox.theplatform.com_80",
"indemand.promoadmin.test.corp.theplatform.com_80",
"indemand.search.sandbox.corp.tp.com_80",
"indemand.support.sandbox.tp.com_443",
"indemand.support.storefront.corp.tp.com_443",
"indemand.timewarner.sandbox.tp.com_80",
"index.search.sample.test.corp.theplatform.com_80",
"index.search.sandbox.corp.theplatform.com_80",
"ingest-stub.ingest.sandbox.tp.com_80",
"ingest-stub.ingest.test.corp.tp.com_80",
"ingest.sandbox.tp.com_80",
"ingest.self.corp.theplatform.com_80",
"ingest.test.corp.theplatform.com_80",
"installer.manage.test.corp.theplatform.com_80",
"installer.mpx.long.test.corp.theplatform.com_80",
"installer.mpx.sandbox.theplatform.com_80",
"installer.mpx.self.corp.theplatform.com_80",
"installer.mpx.short.test.corp.theplatform.com_80",
"ledger.commerce.sandbox.corp.tp.com_80",
"ledger.commerce.sandbox.theplatform.com_80",
"legacy.entitlement.sandbox.theplatform.com_80",
"legacy.entitlement.test.corp.theplatform.com_80",
"lgi.ingest.sandbox.theplatform.com_80",
"license.alu.sandbox.theplatform.com_80",
"license.entitlement.sandbox.theplatform.com_80",
"license.self.corp.theplatform.com_80",
"link.sandbox.tp.com_80",
"link.self.corp.theplatform.com_80",
"link.test.corp.tp.com_80",
"ls_internal_release.corp.tp.com_80",
"manage.sandbox.tp.com_443",
"manage.sandbox.tp.com_80",
"mediamanager.sandbox.tp.com_80",
"mediamanager.theplatform.com_80",
"mps.test.corp.theplatform.com_443",
"mps.test.corp.theplatform.com_80",
"mpsdeleter.test.corp.theplatform.com_80",
"mpx.long.test.corp.theplatform.com_80",
"mpx.self.corp.theplatform.com_80",
"mpx.short.test.corp.theplatform.com_80",
"mpx.test.corp.theplatform.com_80",
"nocache.data.media.perf.sandbox.corp.theplatform.com_80",
"order.commerce.sandbox.corp.tp.com_80",
"order.commerce.sandbox.theplatform.com_80",
"origin.pdk.test.corp.theplatform.com_80",
"origin.pdk.theplatform.com_80",
"payment.commerce.sandbox.corp.tp.com_80",
"payment.commerce.sandbox.theplatform.com_80",
"perf.sandbox.tp.com_80",
"player.sandbox.theplatform.com_443",
"player.sandbox.theplatform.com_80",
"player.test.corp.theplatform.com_443",
"player.test.corp.theplatform.com_80",
"playready.entitlement.sandbox.theplatform.com_80",
"polls.community.sandbox.tp.com_80",
"primary.master.mds.solr.self.theplatform.com_80",
"profile.publish.test.corp.tp.com_80",
"promoadmin.commerce.sandbox.theplatform.com_443",
"promoadmin.commerce.test.corp.theplatform.com_80",
"promotion.commerce.sandbox.theplatform.com_80",
"promotion.commerce.test.corp.theplatform.com_80",
"publish.sandbox.theplatform.com_80",
"publish.self.corp.theplatform.com_80",
"publish.test.corp.tp.com_80",
"qctool.indemand.sandbox.corp.tp.com_443",
"qctool.indemand.sandbox.corp.tp.com_80",
"query.search.mds.perf.sandbox.corp.theplatform.com_80",
"query.search.mds.sandbox.corp.theplatform.com_80",
"query.search.mds.self.corp.theplatform.com_80",
"query.search.mds.test.corp.theplatform.com_80",
"query.search.sample.test.corp.theplatform.com_80",
"query.search.sandbox.corp.theplatform.com_80",
"ratings.community.sandbox.tp.com_80",
"read.data.entertainment.tv.sandbox.theplatform.com_80",
"read.data.entertainment.tv.test.corp.theplatform.com_80",
"read.data.listing.tv.sandbox.theplatform.com_80",
"read.data.listing.tv.test.corp.theplatform.com_80",
"read.data.media.perf.sandbox.corp.theplatform.com_80",
"read.data.media.sandbox.corp.theplatform.com_80",
"read.mps.sandbox.tp.com_80",
"read.mps.test.corp.theplatform.com_80",
"read.sample.test.corp.theplatform.com_80",
"read.testwebb.corp.theplatform.com_80",
"register.alu.sandbox.theplatform.com_443",
"register.alu.sandbox.theplatform.com_80",
"register.alu.theplatform.com-demo_443",
"register.alu.theplatform.com-demo_80",
"release.sandbox.tp.com_443",
"release.sandbox.tp.com_80",
"reporting.community.sandbox.tp.com_80",
"sample.index.search.sandbox.theplatform.comi8081",
"sample.index.search.test.corp.tp.com_8081",
"sample.sandbox.theplatform.com_80",
"sample.test.corp.tp.com_80",
"scheduler.alu.sandbox.theplatform.com_443",
"scheduler.alu.sandbox.theplatform.com_80",
"scheduler.alu.theplatform.com-demo_443",
"scheduler.alu.theplatform.com-demo_80",
"search.mpx.splunk.sandbox.corp.theplatform.com_8089",
"shoppingcart.commerce.sandbox.corp.tp.com_80",
"sky.concurrency.sandbox.theplatform.com_80",
"socialdata.self.corp.theplatform.com_80",
"somd.test.corp.theplatform.com_80",
"sorry.data.media.perf.sandbox.corp.theplatform.com_80",
"sorry.data.media.sandbox.corp.theplatform.com_80",
"stg-admin.access.auth.corp.tp.com_443",
"stg-admin.access.auth.corp.tp.com_80",
"stg-admin.access.auth.tp.com_443",
"stg-admin.access.auth.tp.com_80",
"stg-admin.identity.auth.corp.tp.com_443",
"stg-admin.identity.auth.corp.tp.com_80",
"stg-admin.identity.auth.theplatform.com_443",
"stg-admin.identity.auth.theplatform.com_80",
"stg-apingest.tp.com_80",
"stg-authz.corp.tp.com_443",
"stg-authz.corp.tp.com_80",
"stg-authz.tp.com_443",
"stg-avalon.corp.tp.com_80",
"stg-avalon.tp.com_80",
"stg-cap.corp.tp.com_80",
"stg-cbsnotifications.tp.com_80",
"stg-ccdn.admin.tp.com_80",
"stg-cnbcbusvideo.corp.tp.com_80",
"stg-cnbcbusvideo.tp.com_80",
"stg-cnbcdowschedule.corp.tp.com_80",
"stg-cnbcvideo.corp.tp.com_80",
"stg-cnbcvideo.tp.com_80",
"stg-cstv.corp.tp.com_80",
"stg-cstv.tp.com_80",
"stg-ext.manage_443",
"stg-ext.manage_80",
"stg-ext.totaltags_80",
"stg-ext.user_access_auth_80",
"stg-fancast.store.indemand.tp.com_443",
"stg-fancast.store.indemand.tp.com_80",
"stg-index.ap.tp.com_22",
"stg-index.ap.tp.com_80",
"stg-ingestwizard.tp.com_80",
"stg-int.player.corp.tp.com_443",
"stg-int.player.corp.tp.com_80",
"stg-int.playerdata_80",
"stg-manage.corp.tp.com_443",
"stg-manage.corp.tp.com_80",
"stg-manage.data.corp.tp.com_443",
"stg-manage.data.corp.tp.com_80",
"stg-manage.data.tp.com_443",
"stg-manage.data.tp.com_80",
"stg-pdk.corp.tp.com_80",
"stg-pdk.tp.com_80",
"stg-player.admin.corp.tp.com_443",
"stg-player.admin.corp.tp.com_80",
"stg-player.admin.theplatform.com_443",
"stg-player.data.corp.tp.com_443",
"stg-player.data.tp.com_443",
"stg-player.data.tp.com_80",
"stg-player.theplatform.com_80",
"stg-promo-cstv.corp.tp.com_80",
"stg-qc.indemand.tp.com_443",
"stg-qc.indemand.tp.com_80",
"stg-registry.corp.theplatform.com_80",
"stg-registry_80",
"stg-reports.cstv.tp.com_80",
"stg-reportscstv.corp.tp.com_80",
"stg-search.ap.tp.com_80",
"stg-support.corp.tp.com_80",
"stg-support.tp.com_80",
"stg-twc.store.indemand.tp.com_443",
"stg-twc.store.indemand.tp.com_80",
"stg-user.access.auth.corp.tp.com_443",
"stg-user.access.auth.corp.tp.com_80",
"stg-user.access.auth.tp.com_443",
"stg-user.identity.auth.corp.tp.com_443",
"stg-user.identity.auth.corp.tp.com_80",
"stg-user.identity.auth.theplatform.com_443",
"stg-user.identity.auth.theplatform.com_80",
"storefront.commerce.sandbox.theplatform.com_443",
"storefront.commerce.sandbox.theplatform.com_80",
"storefront.commerce.test.corp.theplatform.com_80",
"tags.community.sandbox.tp.com_80",
"task.sandbox.corp.tp.com_80",
"task.sandbox.tp.com_443",
"task.sandbox.tp.com_80",
"tax.commerce.sandbox.corp.tp.com_80",
"tax.commerce.sandbox.theplatform.com_80",
"teliasonera.userprofiles.community.sandbox.theplatform.com_443",
"teliasonera.userprofiles.community.sandbox.theplatform.com_80",
"telstra.devicereg.sandbox.theplatform.com_80",
"telstra.devicereg.test.corp.theplatform.com_80",
"test-address.commerce.corp.theplatform.com_80",
"test-apingest.corp.tp.com_80",
"test-authz.corp.tp.com_443",
"test-authz.corp.tp.com_80",
"test-cart.indemand.corp.tp.com_80",
"test-checkout.indemand.corp.tp.com_80",
"test-euns.commerce.corp.theplatform.com_80",
"test-fancast.indemand.storefront.corp.theplatform.com_80",
"test-fulfillment.commerce.corp.theplatform.com_80",
"test-indemand.checkout.commerce.corp.theplatform.com_80",
"test-indemand.connector.corp.tp.com_80",
"test-indemand.index.corp.tp.com_80",
"test-indemand.loomia.corp.tp.com_80",
"test-indemand.loomia.tp.com_80",
"test-indemand.search.corp.tp.com_80",
"test-indemand.support.corp.tp.com_80",
"test-index.ap.corp.tp.com_18983",
"test-index.ap.corp.tp.com_80",
"test-int.playerdata_80",
"test-ledger.commerce.corp.theplatform.com_80",
"test-manage.corp.tp.com_443",
"test-manage.corp.tp.com_80",
"test-manage.data.corp.tp.com_443",
"checkout.commerce.perf.corp.theplatform.com_80",
"test-manage.data.corp.tp.com_80",
"test-order.commerce.corp.theplatform.com_80",
"test-order.indemand.corp.tp.com_80",
"test-payment.commerce.corp.theplatform.com_80",
"test-payment.indemand.corp.theplatform.com_80",
"test-pdk.corp.tp.com_80",
"test-player.admin.corp.tp.com_443",
"test-player.admin.corp.tp.com_80",
"test-player.corp.tp.com_443",
"test-player.corp.tp.com_80",
"test-player.data.corp.tp.com_443",
"test-qc.indemand.corp.tp.com_80",
"test-registry.corp.tp.com_80",
"test-roadrunner.indemand.storefront.corp.tp.com_80",
"test-search.ap.corp.tp.com_80",
"test-shoppingcart.commerce.corp.theplatform.com_80",
"test-tax.commerce.corp.theplatform.com_80",
"test-tax.indemand.corp.theplatform.com_80",
"test-transaction.indemand.corp.theplatform.com_80",
"testconnector_80",
"testlicensea.corp.tp.com_80",
"testphysperf.test.corp.tp.com_80",
"testphysperfone.test.corp.tp.com_80",
"testportal.corp.tp.com",
"testprosvc01_80",
"testprosvc01_8080",
"testrelb.corp.tp.com_443",
"testrelb.corp.tp.com_80",
"testservices.corp.tp.com_80",
"testsqlweb.corp.tp.com_80",
"testtaskb.corp.tp.com_443",
"testtaskb.corp.tp.com_80",
"testvmperf.test.corp.tp.com",
"testvmperfone.test.corp.tp.com_80",
"testwebb.corp.tp.com_443",
"tools.test.corp.tp.com_443",
"tools.test.corp.tp.com_80",
"totalratings.community.sandbox.tp.com_80",
"totalvotes.community.sandbox.tp.com_80",
"tpconfluence.corp.theplatform.com_443",
"tpconfluence.corp.theplatform.com_80",
"transfer.sandbox.tp.com_443",
"transfer.sandbox.tp.com_80",
"transfer.test.corp.tp.com_80",
"userlists.community.sandbox.tp.com_80",
"userprofile.self.corp.theplatform.com_80",
"userprofiles.community.sandbox.tp.com_80",
"validation.sandbox.tp.com_80",
"validation.self.corp.theplatform.com_80",
"validation.test.corp.tp.com_80",
"vids.test.corp.theplatform.com_80",
"votes.community.sandbox.tp.com_80",
"watchfolder.ingest.sandbox.theplatform.com_443",
"watchfolder.ingest.sandbox.tp.com_80",
"watchfolder.ingest.test.corp.theplatform.com_80",
"web.sandbox.theplatform.com_80",
"web.test.corp.theplatform.com_80",
"wm.entitlement.sandbox.theplatform.com_443",
"wm.entitlement.test.corp.theplatform.com_443",
"workflow.test.corp.tp.com_80",
"working-manage.corp.tp.com_443",
"working-manage.corp.tp.com_80",
"working-manage.data.corp.tp.com_80",
"zeri.sandbox.theplatform.com_80",
"checkout.commerce.sandbox.theplatform.com_443",
"query.search.mds.perf.corp.theplatform.com_80",
"identity.auth.perf.corp.theplatform.com_443",
"fulfillment.commerce.perf.corp.theplatform.com_80",
"shard.data.workflow.sandbox.theplatform.com_80",
"shard.data.entertainment.tv.sandbox.theplatform.com_443",
"payment.commerce.perf.corp.theplatform.com_80",
"fulfillment.commerce.sandbox.theplatform.com_443",
"euid.perf.corp.theplatform.com_80",
"access.auth.perf.corp.theplatform.com_80",
"euns.commerce.sandbox.corp.tp.com_443",
"data.media.dev.corp.theplatform.com_80",
"primary.master.mds.solr.perf.corp.theplatform.com_80",
"pdk.long.test.corp.theplatform.com_80",
"data.task.dev.corp.theplatform.com_80",
"feed.sample.test.corp.theplatform.com_80",
"pdk.long.test.corp.theplatform.com_443",
"upload.mpx.sandbox.theplatform.com_80",
"pdk.short.test.corp.theplatform.com_443",
"data.task.perf.corp.theplatform.com_80",
"ledger.commerce.sandbox.theplatform.com_443",
"admin.storefront.commerce.perf.corp.theplatform.com_80",
"license.entitlement.test.corp.theplatform.com_80",
"order.commerce.sandbox.theplatform.com_443",
"stg-admin.identity.auth.theplatform.com_81-test",
"shard.data.workflow.sandbox.theplatform.com_443",
"data.configuration.commerce.sandbox.theplatform.com_443",
"tax.commerce.sandbox.theplatform.com_443",
"shard.data.media.sandbox.theplatform.com_443",
"pdk.short.test.corp.theplatform.com_80",
"pdk.sandbox.theplatform.com_443",
"order.commerce.perf.corp.theplatform.com_80",
"lgi.ingest.test.corp.theplatform.com_80",
"payment.commerce.sandbox.theplatform.com_443",
"upload.mpx.sandbox.theplatform.com_443",
"shard.data.media.sandbox.theplatform.com_80",
"feedservice.product.alu.sandbox.theplatform.com_443"]

# set up to loop through an array of vs names
# but currentl only accepts single vs name via cmd line
non_http_vs_list =[]
has_http = false
vs_list.each do |cur_vs|
  #pp cur_vs
  my_profiles = get_vs_profile(lb, [cur_vs])
  #pp my_profiles
  
  my_profiles.first.each do |prof|
    if prof.profile_type.eql?("PROFILE_TYPE_HTTP")
      has_http = true
    
    end
  end
  unless has_http
    non_http_vs_list << cur_vs
  end
  has_http = false
end

pp non_http_vs_list
# 5.times {pp "---------------"}
# pp "count of all vs #{vs_list.count}"
# pp "count of dupe vs w/o http #{non_http_vs_list.count}"